//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD_DiplomadoUASD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public int Id_Departamento { get; set; }
        public string Descripcion { get; set; }
        public string Adm_Departamento { get; set; }
        public string Dependencia { get; set; }
        public string Local { get; set; }
        public string Cargo { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
    
        public virtual Empleado Empleado { get; set; }
    }
}
