USE [master]
GO

/****** Object:  Database [ProductoDB]    Script Date: 8/7/2020 5:29:39 PM ******/
DROP DATABASE [ProductoDB]
GO

/****** Object:  Database [ProductoDB]    Script Date: 8/7/2020 5:29:39 PM ******/
CREATE DATABASE [ProductoDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ProductoDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.ISD\MSSQL\DATA\ProductoDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ProductoDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.ISD\MSSQL\DATA\ProductoDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProductoDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProductoDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProductoDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProductoDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProductoDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProductoDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProductoDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ProductoDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProductoDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProductoDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProductoDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProductoDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProductoDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProductoDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProductoDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProductoDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ProductoDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProductoDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProductoDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ProductoDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProductoDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProductoDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProductoDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProductoDB] SET RECOVERY FULL 
GO

ALTER DATABASE [ProductoDB] SET  MULTI_USER 
GO

ALTER DATABASE [ProductoDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProductoDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProductoDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProductoDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProductoDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProductoDB] SET QUERY_STORE = OFF
GO

USE [ProductoDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [ProductoDB] SET  READ_WRITE 
GO


